### ISSUE TITLE
Cant directly modify bulb with irregular name.

### ISSUE THREAD

**Issue by seanogdev** [stroebjo/alfred-lifx#1]
The name of my bulb is "Sean's Lifx bulb", & therefore when I try to change it directly, it says "No bulb found with label Sean's\ Lifx Bulb". Toggling all bulbs arent an issue though!

Love this workflow btw!

**Comment by stroebjo** [comment]
Thanks for your feedback! :-)

I just pushed a fix which should fix this issue.
